name = "tutorial-api"
main = "src/index.ts"
compatibility_date = "2023-12-01"

[[d1_databases]]
binding = "todo_database"
database_name = "todo-database"
database_id = "857b71ba-af25-47f1-a84d-02ecf007c0bc"


[[r2_buckets]]
binding = "BUCKET"
bucket_name = "tutorial-images"
preview_bucket_name = "tutorial-images"
